In [1]:
import numpy as np
iris=np.genfromtxt(r'C:\Users\abine\OneDrive\Documents\Datasets\Iris\iras.csv',delimiter=',',dtype=[('sepallength','f4'),('sepalwidth','f4'),('petallength','f4'),('petalwidth','f4'),('species','S20')])
names=("sepallength","sepalwidth","petallength","petalwidth","species")
iris
n1=np.array(iris)
print(n1)



[(nan, nan, nan, nan, b'"variety"') (5.1, 3.5, 1.4, 0.2, b'"Setosa"')
 (4.9, 3. , 1.4, 0.2, b'"Setosa"') (4.7, 3.2, 1.3, 0.2, b'"Setosa"')
 (4.6, 3.1, 1.5, 0.2, b'"Setosa"') (5. , 3.6, 1.4, 0.2, b'"Setosa"')
 (5.4, 3.9, 1.7, 0.4, b'"Setosa"') (4.6, 3.4, 1.4, 0.3, b'"Setosa"')
 (5. , 3.4, 1.5, 0.2, b'"Setosa"') (4.4, 2.9, 1.4, 0.2, b'"Setosa"')
 (4.9, 3.1, 1.5, 0.1, b'"Setosa"') (5.4, 3.7, 1.5, 0.2, b'"Setosa"')
 (4.8, 3.4, 1.6, 0.2, b'"Setosa"') (4.8, 3. , 1.4, 0.1, b'"Setosa"')
 (4.3, 3. , 1.1, 0.1, b'"Setosa"') (5.8, 4. , 1.2, 0.2, b'"Setosa"')
 (5.7, 4.4, 1.5, 0.4, b'"Setosa"') (5.4, 3.9, 1.3, 0.4, b'"Setosa"')
 (5.1, 3.5, 1.4, 0.3, b'"Setosa"') (5.7, 3.8, 1.7, 0.3, b'"Setosa"')
 (5.1, 3.8, 1.5, 0.3, b'"Setosa"') (5.4, 3.4, 1.7, 0.2, b'"Setosa"')
 (5.1, 3.7, 1.5, 0.4, b'"Setosa"') (4.6, 3.6, 1. , 0.2, b'"Setosa"')
 (5.1, 3.3, 1.7, 0.5, b'"Setosa"') (4.8, 3.4, 1.9, 0.2, b'"Setosa"')
 (5. , 3. , 1.6, 0.2, b'"Setosa"') (5. , 3.4, 1.6, 0.4, b'"Setosa"')
 (5.2, 3.5, 1.5, 0.2, b'"Setosa"'

In [15]:
print(n2[0:,[0,2]])  #all the values of first and second coloumn

[[nan nan]
 [5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]
 [5.4 1.7]
 [4.6 1.4]
 [5.  1.5]
 [4.4 1.4]
 [4.9 1.5]
 [5.4 1.5]
 [4.8 1.6]
 [4.8 1.4]
 [4.3 1.1]
 [5.8 1.2]
 [5.7 1.5]
 [5.4 1.3]
 [5.1 1.4]
 [5.7 1.7]
 [5.1 1.5]
 [5.4 1.7]
 [5.1 1.5]
 [4.6 1. ]
 [5.1 1.7]
 [4.8 1.9]
 [5.  1.6]
 [5.  1.6]
 [5.2 1.5]
 [5.2 1.4]
 [4.7 1.6]
 [4.8 1.6]
 [5.4 1.5]
 [5.2 1.5]
 [5.5 1.4]
 [4.9 1.5]
 [5.  1.2]
 [5.5 1.3]
 [4.9 1.4]
 [4.4 1.3]
 [5.1 1.5]
 [5.  1.3]
 [4.5 1.3]
 [4.4 1.3]
 [5.  1.6]
 [5.1 1.9]
 [4.8 1.4]
 [5.1 1.6]
 [4.6 1.4]
 [5.3 1.5]
 [5.  1.4]
 [7.  4.7]
 [6.4 4.5]
 [6.9 4.9]
 [5.5 4. ]
 [6.5 4.6]
 [5.7 4.5]
 [6.3 4.7]
 [4.9 3.3]
 [6.6 4.6]
 [5.2 3.9]
 [5.  3.5]
 [5.9 4.2]
 [6.  4. ]
 [6.1 4.7]
 [5.6 3.6]
 [6.7 4.4]
 [5.6 4.5]
 [5.8 4.1]
 [6.2 4.5]
 [5.6 3.9]
 [5.9 4.8]
 [6.1 4. ]
 [6.3 4.9]
 [6.1 4.7]
 [6.4 4.3]
 [6.6 4.4]
 [6.8 4.8]
 [6.7 5. ]
 [6.  4.5]
 [5.7 3.5]
 [5.5 3.8]
 [5.5 3.7]
 [5.8 3.9]
 [6.  5.1]
 [5.4 4.5]
 [6.  4.5]
 [6.7 4.7]
 [6.3 4.4]
 [5.6 4.1]
 [5.5 4. ]

In [11]:
print(n1["sepallength"])

[nan 5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4
 5.1 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9
 5.  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9
 5.5 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9
 6.1 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6
 5.5 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9
 7.3 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7
 7.2 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8
 6.8 6.7 6.7 6.3 6.5 6.2 5.9]


In [ ]:
#1find mean,median and standard deviation of iris sepal lenght and petal length
#2filter the rows of iris that has petal length >1.5 and sepal length <5
#

In [12]:
#1
n2=np.genfromtxt(r'C:\Users\abine\OneDrive\Documents\Datasets\Iris\iras.csv',delimiter=',',dtype='float',usecols=[0,1,2,3])
n2
#print(n2[0:,[0,2]])
n3=(n2[0:,[0,2]])
print(n3)
n3[np.isnan(n3)]=0
me=np.mean(n3[0:,[0]])
print("sepal length mean =",me)
me1=np.mean(n3[0:,[1]])   # here we have to give the 1 instead of the index number
print("petal length mean = " ,me1)
md=np.median(n3[0:,[0]])
print("sepal length median = ",md)
md1=np.median(n3[0:,[1]])
print("petal length median = ",md1)
sd=np.std(n3[0:,[0]])
print("sepal length standard deviation =",sd)
sd1=np.std(n3[0:,[1]])
print("petal length standard deviation =",sd1)

[[nan nan]
 [5.1 1.4]
 [4.9 1.4]
 [4.7 1.3]
 [4.6 1.5]
 [5.  1.4]
 [5.4 1.7]
 [4.6 1.4]
 [5.  1.5]
 [4.4 1.4]
 [4.9 1.5]
 [5.4 1.5]
 [4.8 1.6]
 [4.8 1.4]
 [4.3 1.1]
 [5.8 1.2]
 [5.7 1.5]
 [5.4 1.3]
 [5.1 1.4]
 [5.7 1.7]
 [5.1 1.5]
 [5.4 1.7]
 [5.1 1.5]
 [4.6 1. ]
 [5.1 1.7]
 [4.8 1.9]
 [5.  1.6]
 [5.  1.6]
 [5.2 1.5]
 [5.2 1.4]
 [4.7 1.6]
 [4.8 1.6]
 [5.4 1.5]
 [5.2 1.5]
 [5.5 1.4]
 [4.9 1.5]
 [5.  1.2]
 [5.5 1.3]
 [4.9 1.4]
 [4.4 1.3]
 [5.1 1.5]
 [5.  1.3]
 [4.5 1.3]
 [4.4 1.3]
 [5.  1.6]
 [5.1 1.9]
 [4.8 1.4]
 [5.1 1.6]
 [4.6 1.4]
 [5.3 1.5]
 [5.  1.4]
 [7.  4.7]
 [6.4 4.5]
 [6.9 4.9]
 [5.5 4. ]
 [6.5 4.6]
 [5.7 4.5]
 [6.3 4.7]
 [4.9 3.3]
 [6.6 4.6]
 [5.2 3.9]
 [5.  3.5]
 [5.9 4.2]
 [6.  4. ]
 [6.1 4.7]
 [5.6 3.6]
 [6.7 4.4]
 [5.6 4.5]
 [5.8 4.1]
 [6.2 4.5]
 [5.6 3.9]
 [5.9 4.8]
 [6.1 4. ]
 [6.3 4.9]
 [6.1 4.7]
 [6.4 4.3]
 [6.6 4.4]
 [6.8 4.8]
 [6.7 5. ]
 [6.  4.5]
 [5.7 3.5]
 [5.5 3.8]
 [5.5 3.7]
 [5.8 3.9]
 [6.  5.1]
 [5.4 4.5]
 [6.  4.5]
 [6.7 4.7]
 [6.3 4.4]
 [5.6 4.1]
 [5.5 4. ]

In [21]:
#2
n4=n2[n2[0:,0]<5]
print("rows that have sepal length <5 = ",n4)


rows that have sepal length <5 =  [[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [4.6 3.6 1.  0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in less
  


In [27]:
n5=n3[n3[0:,2]<1.5]
print("rows that havepetal length<1.5 ",n5)

IndexError: index 2 is out of bounds for axis 1 with size 2

In [28]:
#3corrcoeff
ce=np.corrcoef(n3[0:,0],n3[0:,1])[0,1]
print("correlationcoefficient of sepal length and petal length = ",ce)

correlationcoefficient of sepal length and petal length =  0.8296807022492464


In [29]:
#unique
u=np.unique(n3[0:,0])
print("unique values of sepal length and petal length = ",u)

unique values of sepal length and petal length =  [0.  4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9
 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6 7.7 7.9]


In [68]:
#percentile
p=np.percentile(n3[0:,0],25)
print("25th percentile of sepal length = ",p)

25th percentile of sepal length =  5.1


In [70]:
#sort
s=np.sort(n3[0:,0])
print("sort for sepal length coloumn",s)

sort for sepal length coloumn [0.  4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9
 4.9 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5
 5.5 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.
 6.1 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.3 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3
 7.4 7.6 7.7 7.7 7.7 7.7 7.9]


In [9]:
#sort and order
so=np.sort(iris,order="sepallength")
print("sort and order =",so)

sort and order = [(4.3, 3. , 1.1, 0.1, b'"Setosa"') (4.4, 2.9, 1.4, 0.2, b'"Setosa"')
 (4.4, 3. , 1.3, 0.2, b'"Setosa"') (4.4, 3.2, 1.3, 0.2, b'"Setosa"')
 (4.5, 2.3, 1.3, 0.3, b'"Setosa"') (4.6, 3.1, 1.5, 0.2, b'"Setosa"')
 (4.6, 3.2, 1.4, 0.2, b'"Setosa"') (4.6, 3.4, 1.4, 0.3, b'"Setosa"')
 (4.6, 3.6, 1. , 0.2, b'"Setosa"') (4.7, 3.2, 1.3, 0.2, b'"Setosa"')
 (4.7, 3.2, 1.6, 0.2, b'"Setosa"') (4.8, 3. , 1.4, 0.1, b'"Setosa"')
 (4.8, 3. , 1.4, 0.3, b'"Setosa"') (4.8, 3.1, 1.6, 0.2, b'"Setosa"')
 (4.8, 3.4, 1.6, 0.2, b'"Setosa"') (4.8, 3.4, 1.9, 0.2, b'"Setosa"')
 (4.9, 2.4, 3.3, 1. , b'"Versicolor"')
 (4.9, 2.5, 4.5, 1.7, b'"Virginica"') (4.9, 3. , 1.4, 0.2, b'"Setosa"')
 (4.9, 3.1, 1.5, 0.1, b'"Setosa"') (4.9, 3.1, 1.5, 0.2, b'"Setosa"')
 (4.9, 3.6, 1.4, 0.1, b'"Setosa"') (5. , 2. , 3.5, 1. , b'"Versicolor"')
 (5. , 2.3, 3.3, 1. , b'"Versicolor"') (5. , 3. , 1.6, 0.2, b'"Setosa"')
 (5. , 3.2, 1.2, 0.2, b'"Setosa"') (5. , 3.3, 1.4, 0.2, b'"Setosa"')
 (5. , 3.4, 1.5, 0.2, b'"Setosa"') (

In [ ]:
#argsort
#iris[iris[0:,1].argsort()][::-1]