In [1]:
import numpy as np
wine=np.genfromtxt(r'C:\Users\abine\OneDrive\Documents\Datasets\wine_quality\winequality-red.csv',delimiter=';',dtype=[('fixed acidity','f4'),('volatile acidity','f4'),('citric acid','f4'),('residual sugar','f4'),('chlorides','f4'),('free sulfur dioxide','f4'),('total sulfur dioxide','f4'),('density','f4'),('pH','f4'),('sulphates','f4'),('alcohol','f4'),('quality','i4')])
wine

array([(nan,   nan,  nan, nan,   nan, nan, nan,     nan,  nan,  nan,  nan, -1),
       (7.4, 0.7  , 0.  , 1.9, 0.076, 11., 34., 0.9978 , 3.51, 0.56,  9.4,  5),
       (7.8, 0.88 , 0.  , 2.6, 0.098, 25., 67., 0.9968 , 3.2 , 0.68,  9.8,  5),
       ...,
       (6.3, 0.51 , 0.13, 2.3, 0.076, 29., 40., 0.99574, 3.42, 0.75, 11. ,  6),
       (5.9, 0.645, 0.12, 2. , 0.075, 32., 44., 0.99547, 3.57, 0.71, 10.2,  5),
       (6. , 0.31 , 0.47, 3.6, 0.067, 18., 42., 0.99549, 3.39, 0.66, 11. ,  6)],
      dtype=[('fixed_acidity', '<f4'), ('volatile_acidity', '<f4'), ('citric_acid', '<f4'), ('residual_sugar', '<f4'), ('chlorides', '<f4'), ('free_sulfur_dioxide', '<f4'), ('total_sulfur_dioxide', '<f4'), ('density', '<f4'), ('pH', '<f4'), ('sulphates', '<f4'), ('alcohol', '<f4'), ('quality', '<i4')])

In [2]:
wine2=np.genfromtxt(r'C:\Users\abine\OneDrive\Documents\Datasets\wine_quality\winequality-red.csv',delimiter=';',dtype='float',usecols=[8,10,11])
wine2

array([[  nan,   nan,   nan],
       [ 3.51,  9.4 ,  5.  ],
       [ 3.2 ,  9.8 ,  5.  ],
       ...,
       [ 3.42, 11.  ,  6.  ],
       [ 3.57, 10.2 ,  5.  ],
       [ 3.39, 11.  ,  6.  ]])

In [3]:
#indexing
wine3=(wine2[:,2])
wine3

array([nan,  5.,  5., ...,  6.,  5.,  6.])

In [4]:
wine3[np.isnan(wine3)]=0

In [5]:
#mean for quality
me=np.mean(wine3)
print("wine quality mean =",me)

wine quality mean = 5.6325


In [6]:
wine3

array([0., 5., 5., ..., 6., 5., 6.])

In [65]:
#median for quality
md=np.median(wine3)
print("wine quality median = ",md)

wine quality median =  0.26


In [66]:
#standard deviation for quality
mo=np.std(wine3)
print("wine quality standard deviation = ",mo)

wine quality standard deviation =  0.19479710588439836


In [56]:
#indexing
wine4=(wine2[:,1]
wine4


array([  nan, 0.7  , 0.88 , ..., 0.51 , 0.645, 0.31 ])

In [61]:
#mean for alcohol percentage
wine4[np.isnan(wine4)]=0
me1=np.mean(wine4)
print(" mean alcohol % = ",me1)

 mean alcohol % =  0.527490625


In [63]:
# median for alcohol percentage
mo1=np.median(wine4)
print("median for alcohol percentage = ",mo1)

median for alcohol percentage =  0.52


In [64]:
#standard deviation for alcohol percentage
sd1=np.std(wine4)
print("standard deviation for alcohol percentage = ",sd1)

standard deviation for alcohol percentage =  0.17943330909312624


In [72]:
#sort and order
so=np.sort(wine,order="quality")
print("sortand order for quality coloumn",so)

sortand order for quality coloumn [( nan,   nan,  nan, nan,   nan, nan, nan,     nan,  nan,  nan,   nan, -1)
 ( 6.7, 0.76 , 0.02, 1.8, 0.078,  6., 12., 0.996  , 3.55, 0.63,  9.95,  3)
 ( 6.8, 0.815, 0.  , 1.2, 0.267, 16., 29., 0.99471, 3.32, 0.51,  9.8 ,  3)
 ...
 (10.7, 0.35 , 0.53, 2.6, 0.07 ,  5., 16., 0.9972 , 3.15, 0.65, 11.  ,  8)
 (11.3, 0.62 , 0.67, 5.2, 0.086,  6., 19., 0.9988 , 3.22, 0.69, 13.4 ,  8)
 (12.6, 0.31 , 0.72, 2.2, 0.072,  6., 29., 0.9987 , 2.88, 0.82,  9.8 ,  8)]
